<?php namespace YnievesDotNetTeam\QvaPay;

use System\Classes\BaseExtension;

/**
 * Tiab Extension Information File
 */
class Extension extends BaseExtension
{

    /**
     * Register method, called when the extension is first registered.
     *
     * @return void
     */
    public function register()
    {

    }

    /**
     * Boot method, called right before the request route.
     *
     * @return void
     */
    public function boot()
    {

    }

    /**
     * Registers the payment of QvaPay generated by this extension.
     *
     * @return array
     */
    public function registerPaymentGateways()
    {
        return [
            \YnievesDotNetTeam\QvaPay\Payments\QvaPay::class => [
                'code' => 'qvapay',
                'name' => 'QvaPay',
                'description' => 'QvaPay Payment for Tastyigniter',
            ]
        ];
    }
}
